packages:
  - "apps/*"
  - "docs"
  - "packages/*"
allowBuilds:
  "@parcel/watcher": true
  '@prisma/engines': true
  esbuild: true
  lefthook: true
  lmdb: true
  msgpackr-extract: true
  prisma: true
  unrs-resolver: true
